### ISSUE TITLE
vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided

### ISSUE THREAD

**Issue by silverfisk** [BL08FR/Long-range-Esp-Now-Camera#1]
Hi!

Sorry for making an issue if this isn't a bug, but I didn't know how to contact you. Hope this is ok.

I'm trying to compile this project, but get this error. I'm very interested in getting this to work and have ordered two ESP32 CAMs, but right now I'm trying to compile this for this board which is what I have at the moment:

Board: _DOIT ESP32 DEVKIT V1, 80MHz, 921600, None_

Am I using the wrong libraries (or versions) maybe?
https://github.com/me-no-dev/ESPAsyncWebServer.git
https://github.com/me-no-dev/ESPAsyncTCP.git
https://github.com/me-no-dev/AsyncTCP.git

```
/home/redacted/Arduino/Radin-Target-Camera-Long-range-Esp-Now-Camera/ReceiverESP-NOW_v1_1/SPIFFS.cpp: In member function 'virtual bool SPIFFSImpl::exists(const char*)':
SPIFFS.cpp:42:28: error: no matching function for call to 'SPIFFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from /home/redacted/Arduino/Radin-Target-Camera-Long-range-Esp-Now-Camera/ReceiverESP-NOW_v1_1/SPIFFS.cpp:15:
/home/redacted/Arduino/hardware/espressif/esp32/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
/home/redacted/Arduino/hardware/espressif/esp32/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided
exit status 1
no matching function for call to 'SPIFFSImpl::open(const char*&, const char [2])'

```

Trying to compile it in Arduino SDK 1.8.19

**Comment by BL08FR** [comment]
Hello,

It's ok don't worry, you didn't told it but I suppose the sketch you try to compile is the Receiver?
If yes, as you can see, to avoid libraries problem I directly integrated it in the tabs of the .ino file so for me libraries are not a subject at all except maybe if you dowloaded it separately and there is a conflict between libraries in tabs and installed by yourself (of course I can be wrong but I don't believe).

My opinion is that you selected the wrong board and that one don't have SPIFF memory so it's impossible to compile.
You should have to select in Arduino IDE the board : Type of card -> ESP32 Arduino -> AI Thinker ESP32-CAM.
It should suit classic ESP32-CAM of new CH340 model as I used.

Good luck, tell me what happen then!

**Comment by silverfisk** [comment]
Ok, thanks! :)

Now I changed to the AI Thinker ESP32-CAM, removed all my libraries, and the first issue is `AsyncTCP.h: No such file or directory`
Changing
<AsyncTCP.h>
to
"./AsyncTCP.h"

make the compiler go past the issue, until I reach

`AsyncWebSocket.h:34:10: fatal error: AsyncWebSynchronization.h: No such file or directory`

But this file I cannot find. I think it may be in the https://github.com/me-no-dev/ESPAsyncWebServer.git project?

**Comment by BL08FR** [comment]
Hmmm,

First I don't understand why "AsyncTCP.h: No such file or directory" considering this is in the tabs...
Then, it's possible that because I have the library intalled in my folder it seemed to me everything was ok without this "sub library".

All this AsyncWebSocket.h:34:10: fatal error: AsyncWebSynchronization.h are sub-libraries from ESPAsyncwebserver. I join my library, try with it
[ESPAsyncWebServer-master.zip](https://github.com/BL08FR/Radin-Target-Camera-Long-range-Esp-Now-Camera/files/8618405/ESPAsyncWebServer-master.zip)
.

**Comment by silverfisk** [comment]
It seems like the missing AsyncTCP.h files might come from the included libraries:
```
libraries/ESPAsyncWebServer-master/src/ESPAsyncWebServer.h:#include <AsyncTCP.h>
libraries/ESPAsyncWebServer-master/src/AsyncWebSocket.h:#include <AsyncTCP.h>
libraries/ESPAsyncWebServer-master/src/AsyncEventSource.h:#include <AsyncTCP.h>
```
But adding the https://github.com/me-no-dev/AsyncTCP.git to libraries/, the compilation goes on, and then fails at

```
/home/silverfisk/Arduino/Radin-Target-Camera-Long-range-Esp-Now-Camera/ReceiverESP-NOW_v1_1/SPIFFS.cpp: In member function 'virtual bool SPIFFSImpl::exists(const char*)':
SPIFFS.cpp:42:28: error: no matching function for call to 'SPIFFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from /home/silverfisk/Arduino/Radin-Target-Camera-Long-range-Esp-Now-Camera/ReceiverESP-NOW_v1_1/SPIFFS.cpp:15:
/home/silverfisk/.arduino15/packages/esp32/hardware/esp32/2.0.3/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
/home/silverfisk/.arduino15/packages/esp32/hardware/esp32/2.0.3/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided
Using library WiFi at version 2.0.0 in folder: /home/silverfisk/.arduino15/packages/esp32/hardware/esp32/2.0.3/libraries/WiFi 
Using library AsyncTCP at version 1.1.1 in folder: /home/silverfisk/Arduino/libraries/AsyncTCP 
Using library ESPAsyncWebServer at version 1.2.3 in folder: /home/silverfisk/Arduino/libraries/ESPAsyncWebServer 
Using library FS at version 2.0.0 in folder: /home/silverfisk/.arduino15/packages/esp32/hardware/esp32/2.0.3/libraries/FS 
exit status 1
no matching function for call to 'SPIFFSImpl::open(const char*&, const char [2])'
```
I tried both with cleaning out all libraries, and installing your ZIP file, and using the latest GIT version of ESPAsyncWebServer.

The **2.0.3** part got me thinking, perhaps you use version 1 of esp32? So I installed 1.0.6 and now the compilation complains at

```
Pyserial is not installed for /usr/bin/python. Check the README for installation instructions.
Traceback (most recent call last):
  File "/home/silverfisk/.arduino15/packages/esp32/tools/esptool_py/3.0.0/esptool.py", line 38, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
Using library WiFi at version 1.0 in folder: /home/silverfisk/.arduino15/packages/esp32/hardware/esp32/1.0.6/libraries/WiFi 
Using library AsyncTCP at version 1.1.1 in folder: /home/silverfisk/Arduino/libraries/AsyncTCP 
Using library ESPAsyncWebServer at version 1.2.3 in folder: /home/silverfisk/Arduino/libraries/ESPAsyncWebServer 
Using library FS at version 1.0 in folder: /home/silverfisk/.arduino15/packages/esp32/hardware/esp32/1.0.6/libraries/FS 
exit status 1
Error compiling for board AI Thinker ESP32-CAM.
```

But now I have to take a break and rest for a while  :)

**Comment by silverfisk** [comment]
Oh, scratch that. As a last thing I ```python -m pip install pyserial --user``` and now it actually compiled

**Comment by BL08FR** [comment]
I forgot about python, I don't remember why it's needed but it is.
Glad to hear it's ok now!

**Comment by silverfisk** [comment]
Thanks for the help!
Just have to wait for the delivery if esp32 cam then
